/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/analogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analogs
         * @description Похожие товары каталога: TF-IDF по названиям + цена аналога
         */
        get: operations["get_analogs_api_analogs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calculator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Unit Economics
         * @description Маржа до закупки: разбор расходов, налог, прибыль (existing — по SKU из API, manual — вручную)
         */
        post: operations["calculate_unit_economics_api_calculator_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Onboarding Status
         * @description Чек-лист готовности: только БД, без внешних вызовов
         */
        get: operations["get_onboarding_status_api_onboarding_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/check-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Connection
         * @description Реальная проверка ключей Ozon (внешние запросы)
         */
        post: operations["check_connection_api_onboarding_check_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Настройки текущего пользователя
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * Update Settings
         * @description Обновить настройки пользователя
         */
        put: operations["update_settings_api_settings_put"];
        /**
         * Create Settings
         * @description Создать или обновить настройки пользователя
         */
        post: operations["create_settings_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Secrets
         * @description Сохранённые секреты Ozon API для текущего пользователя (маскированные)
         */
        get: operations["get_secrets_api_secrets_get"];
        /**
         * Update Secrets
         * @description Обновить секреты Ozon API и проверить их для текущего пользователя
         */
        put: operations["update_secrets_api_secrets_put"];
        /**
         * Create Secrets
         * @description Создать или обновить секреты Ozon API для текущего пользователя
         */
        post: operations["create_secrets_api_secrets_post"];
        /** Delete Secrets */
        delete: operations["delete_secrets_api_secrets_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Full Report
         * @description Создать полный отчёт
         */
        post: operations["create_full_report_api_reports_full_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/sections/prices-commissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prices Commissions
         * @description Цены и комиссии Ozon по товарам (/v5/product/info/prices)
         */
        get: operations["get_prices_commissions_api_reports_sections_prices_commissions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/sections/product-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Product Cards
         * @description Карточки товаров: комиссии, объёмный вес, цены (/v3/product/info/list)
         */
        post: operations["get_product_cards_api_reports_sections_product_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/sections/finance-expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Finance Expenses
         * @description Финансовые начисления по отправлениям (/v3/finance/transaction/list + totals)
         */
        post: operations["get_finance_expenses_api_reports_sections_finance_expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/sections/seller-rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Seller Rating
         * @description Рейтинг продавца (/v1/rating/summary)
         */
        get: operations["get_seller_rating_api_reports_sections_seller_rating_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/sections/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock Planning
         * @description Планирование поставок: остатки, дни запаса, рекомендуемая поставка (/v1/analytics/turnover/stocks)
         */
        get: operations["get_stock_planning_api_reports_sections_stocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/sections/search-queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Search Queries
         * @description Поисковые фразы: показы, позиции, конверсии (/v1/analytics/product-queries)
         */
        post: operations["get_search_queries_api_reports_sections_search_queries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/sections/cashflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Cashflow
         * @description ДДС-журнал: все операции периода, приход/расход, бегущий баланс
         */
        post: operations["get_cashflow_api_reports_sections_cashflow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/top-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Top Actions
         * @description Агрегированные действия: остатки, замороженный сток, дорогие расходы, спрос без продаж
         */
        post: operations["get_top_actions_api_reports_top_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Status
         * @description Статус отчёта
         */
        get: operations["get_report_status_api_reports_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalogItem
         * @description Аналог товара: сходство и цена
         */
        AnalogItem: {
            /**
             * Sku
             * @description SKU аналога.
             */
            sku: number;
            /**
             * Name
             * @description Название аналога.
             */
            name: string;
            /**
             * Offer Id
             * @description Артикул продавца.
             */
            offer_id?: string | null;
            /**
             * Similarity
             * @description Косинусная близость названия, 0..1.
             */
            similarity: number;
            /**
             * Price
             * @description Цена аналога, ₽ (из /v5/prices).
             */
            price?: number | null;
        };
        /**
         * AnalogsResponse
         * @description Ответ поиска аналогов для SKU
         */
        AnalogsResponse: {
            /**
             * Sku
             * @description SKU исходного товара.
             */
            sku: number;
            /**
             * Name
             * @description Название исходного товара.
             */
            name?: string | null;
            /**
             * Total Catalog
             * @description Размер каталога, по которому искали.
             */
            total_catalog: number;
            /**
             * Analogs
             * @description Топ похожих товаров.
             */
            analogs?: components["schemas"]["AnalogItem"][];
        };
        /**
         * CalculatorCostLine
         * @description Строка расходов в разборе калькулятора
         */
        CalculatorCostLine: {
            /**
             * Name
             * @description Название расхода.
             */
            name: string;
            /**
             * Amount
             * @description Сумма, ₽ на единицу.
             */
            amount: number;
            /**
             * Source
             * @description Источник значения: api / manual / settings.
             * @default manual
             */
            source: string;
        };
        /**
         * CalculatorRequest
         * @description Запрос расчёта плановой юнит-экономики
         */
        CalculatorRequest: {
            /**
             * Mode
             * @description existing — товар на Ozon (данные из API по sku); manual — новинка, всё вручную.
             * @default manual
             * @enum {string}
             */
            mode: "existing" | "manual";
            /**
             * Sku
             * @description SKU товара (обязателен для existing).
             */
            sku?: number | null;
            /**
             * Purchase Price
             * @description Закупочная цена за единицу, ₽.
             */
            purchase_price: number;
            /**
             * Sale Price
             * @description Цена продажи, ₽. existing: берётся из API, если не задана.
             */
            sale_price?: number | null;
            /**
             * Commission Percent
             * @description Комиссия Ozon, % (manual; existing берётся из API).
             */
            commission_percent?: number | null;
            /**
             * Logistics Cost
             * @description Логистика за единицу, ₽ (manual; existing — из API, фоллбэк на настройку).
             */
            logistics_cost?: number | null;
            /**
             * Acquiring Percent
             * @description Эквайринг, % (manual; existing берётся из API).
             */
            acquiring_percent?: number | null;
            /**
             * Ad Budget Percent
             * @description Реклама, % от выручки (переопределяет настройку магазина).
             */
            ad_budget_percent?: number | null;
        };
        /**
         * CalculatorResult
         * @description Результат расчёта плановой юнит-экономики
         */
        CalculatorResult: {
            /**
             * Mode
             * @description Режим расчёта.
             */
            mode: string;
            /**
             * Sku
             * @description SKU (existing).
             */
            sku?: number | null;
            /**
             * Revenue
             * @description Выручка за единицу, ₽.
             */
            revenue: number;
            /**
             * Cost Lines
             * @description Разбор расходов.
             */
            cost_lines?: components["schemas"]["CalculatorCostLine"][];
            /**
             * Total Costs
             * @description Сумма расходов, ₽.
             */
            total_costs: number;
            /**
             * Pre Tax Profit
             * @description Прибыль до налога, ₽.
             */
            pre_tax_profit: number;
            /**
             * Tax
             * @description Налог, ₽.
             */
            tax: number;
            /**
             * Tax System
             * @description Налоговая система.
             */
            tax_system: string;
            /**
             * Profit
             * @description Чистая прибыль за единицу, ₽.
             */
            profit: number;
            /**
             * Margin Percent
             * @description Маржа, % от выручки.
             */
            margin_percent: number;
            /**
             * Markup Percent
             * @description Наценка, % от закупки.
             */
            markup_percent: number;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * CashFlowRow
         * @description Строка ДДС-журнала (операция с бегущим балансом)
         */
        CashFlowRow: {
            /**
             * Date
             * @description Дата операции.
             */
            date?: string | null;
            /**
             * Operation Type
             * @description Тип операции (API).
             */
            operation_type?: string | null;
            /**
             * Operation Type Name
             * @description Название типа операции.
             */
            operation_type_name?: string | null;
            /**
             * Amount
             * @description Сумма: + приход, - расход, ₽.
             */
            amount?: number | null;
            /**
             * Balance After
             * @description Накопленный баланс после операции, ₽.
             */
            balance_after?: number | null;
        };
        /**
         * CashFlowSectionResponse
         * @description Ответ секции «ДДС-журнал»
         */
        CashFlowSectionResponse: {
            /**
             * Section
             * @description Идентификатор секции.
             */
            section: string;
            /**
             * Generated At
             * Format: date-time
             * @description Момент генерации (UTC).
             */
            generated_at: string;
            /**
             * Row Count
             * @description Количество строк в data.
             */
            row_count: number;
            /**
             * Warnings
             * @description Замечания о точности расчёта (фоллбэки на настройки и т.п.).
             */
            warnings?: string[];
            /**
             * Date From
             * @description Начало периода (YYYY-MM-DD).
             */
            date_from: string;
            /**
             * Date To
             * @description Конец периода (YYYY-MM-DD).
             */
            date_to: string;
            /**
             * Total Income
             * @description Сумма приходов, ₽.
             * @default 0
             */
            total_income: number;
            /**
             * Total Expense
             * @description Сумма расходов, ₽.
             * @default 0
             */
            total_expense: number;
            /**
             * Net Flow
             * @description Чистый денежный поток, ₽.
             * @default 0
             */
            net_flow: number;
            /**
             * Type Summary
             * @description Итог по каждому типу операции, ₽.
             */
            type_summary?: {
                [key: string]: number;
            };
            /** Data */
            data?: components["schemas"]["CashFlowRow"][];
        };
        /**
         * CheckConnectionRequest
         * @description Какие подключения проверить (POST /api/onboarding/check-connection)
         */
        CheckConnectionRequest: {
            /**
             * Seller
             * @description Проверить Seller API ключи.
             * @default true
             */
            seller: boolean;
            /**
             * Performance
             * @description Проверить Performance API ключи.
             * @default true
             */
            performance: boolean;
        };
        /**
         * CheckConnectionResponse
         * @description Результат реальной проверки подключений
         */
        CheckConnectionResponse: {
            /**
             * Seller Connected
             * @description Seller API доступен (None — не проверялся).
             */
            seller_connected?: boolean | null;
            /**
             * Performance Connected
             * @description Performance API доступен (None — не проверялся/не настроен).
             */
            performance_connected?: boolean | null;
        };
        /**
         * CreatedReportResponse
         * @description Созданный отчёт
         */
        CreatedReportResponse: {
            /**
             * Request Uuid
             * @description Report request UUID
             */
            request_uuid: string;
            /**
             * Status
             * @description pending | in_progress | completed | failed
             */
            status: string;
        };
        /**
         * FinanceExpenseRow
         * @description Строка секции финансовых начислений (/v3/finance/transaction/list)
         */
        FinanceExpenseRow: {
            /**
             * Sku
             * @description SKU товара.
             */
            sku?: number | null;
            /**
             * Sale Commission
             * @description Комиссия за продажу, ₽ (факт).
             */
            sale_commission?: number | null;
            /**
             * Delivery
             * @description Доставка, ₽ (факт).
             */
            delivery?: number | null;
            /**
             * Return Delivery
             * @description Возвратная доставка, ₽ (факт).
             */
            return_delivery?: number | null;
            /**
             * Services
             * @description Услуги Ozon, ₽ (факт).
             */
            services?: number | null;
            /**
             * Accruals For Sale
             * @description Начислено за продажи, ₽ (факт).
             */
            accruals_for_sale?: number | null;
            /**
             * Actual Logistics Per Unit
             * @description Фактическая логистика на единицу, ₽.
             */
            actual_logistics_per_unit?: number | null;
        };
        /**
         * FinanceExpensesSectionResponse
         * @description Ответ секции «Финансовые начисления»
         */
        FinanceExpensesSectionResponse: {
            /**
             * Section
             * @description Идентификатор секции.
             */
            section: string;
            /**
             * Generated At
             * Format: date-time
             * @description Момент генерации (UTC).
             */
            generated_at: string;
            /**
             * Row Count
             * @description Количество строк в data.
             */
            row_count: number;
            /**
             * Warnings
             * @description Замечания о точности расчёта (фоллбэки на настройки и т.п.).
             */
            warnings?: string[];
            /**
             * Date From
             * @description Начало периода (YYYY-MM-DD).
             */
            date_from: string;
            /**
             * Date To
             * @description Конец периода (YYYY-MM-DD).
             */
            date_to: string;
            /**
             * Totals
             * @description Итоги периода (/v3/finance/transaction/totals).
             */
            totals?: {
                [key: string]: unknown;
            };
            /** Data */
            data?: components["schemas"]["FinanceExpenseRow"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /**
             * Service
             * @default MetrixSense
             */
            service: string;
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
        };
        /**
         * OnboardingStatusResponse
         * @description Статус онбординга: только факты из БД, без внешних вызовов
         */
        OnboardingStatusResponse: {
            /**
             * Seller Api
             * @description {required, configured}.
             */
            seller_api: {
                [key: string]: unknown;
            };
            /**
             * Performance Api
             * @description {required, configured}.
             */
            performance_api: {
                [key: string]: unknown;
            };
            /**
             * Unit Economics Settings
             * @description Текущие настройки юнит-экономики и признак is_default.
             */
            unit_economics_settings: {
                [key: string]: unknown;
            };
            /**
             * Ready For Report
             * @description Seller-ключи сохранены — отчёт можно создать.
             */
            ready_for_report: boolean;
            /**
             * Next Steps
             * @description Что осталось настроить.
             */
            next_steps?: string[];
        };
        /**
         * PlanSummary
         * @description Сводка плана поставки
         */
        PlanSummary: {
            /**
             * Skus Total
             * @description Всего SKU в плане.
             * @default 0
             */
            skus_total: number;
            /**
             * Skus Needs Reorder
             * @description SKU, требующих поставки.
             * @default 0
             */
            skus_needs_reorder: number;
            /**
             * Skus Critical
             * @description SKU с критическим запасом.
             * @default 0
             */
            skus_critical: number;
            /**
             * Total Units To Ship
             * @description Суммарная рекомендуемая поставка, шт.
             * @default 0
             */
            total_units_to_ship: number;
        };
        /**
         * PricesCommissionsRow
         * @description Строка секции цен и комиссий (/v5/product/info/prices)
         */
        PricesCommissionsRow: {
            /**
             * Product Id
             * @description ID товара Ozon.
             */
            product_id?: number | null;
            /**
             * Offer Id
             * @description Артикул продавца.
             */
            offer_id?: string | null;
            /**
             * Price
             * @description Текущая цена, ₽.
             */
            price?: number | null;
            /**
             * Old Price
             * @description Цена до скидки, ₽.
             */
            old_price?: number | null;
            /**
             * Min Price
             * @description Минимальная цена, ₽.
             */
            min_price?: number | null;
            /**
             * Marketing Price
             * @description Цена с учётом акций Ozon, ₽.
             */
            marketing_price?: number | null;
            /**
             * Commission Fbo Percent
             * @description Комиссия за продажу FBO, %.
             */
            commission_fbo_percent?: number | null;
            /**
             * Commission Fbs Percent
             * @description Комиссия за продажу FBS, %.
             */
            commission_fbs_percent?: number | null;
            /**
             * Acquiring Percent
             * @description Эквайринг, %.
             */
            acquiring_percent?: number | null;
            /**
             * Logistics Fbo Range
             * @description Логистика FBO, ₽ (мин–макс).
             */
            logistics_fbo_range?: string | null;
            /**
             * Logistics Fbs First Mile Range
             * @description Первая миля FBS, ₽ (мин–макс).
             */
            logistics_fbs_first_mile_range?: string | null;
            /**
             * Delivery Fbo
             * @description Доставка до покупателя FBO, ₽.
             */
            delivery_fbo?: number | null;
            /**
             * Return Flow Fbo
             * @description Возвратный поток FBO, ₽.
             */
            return_flow_fbo?: number | null;
            /**
             * Volume Weight L
             * @description Объёмный вес, л.
             */
            volume_weight_l?: number | null;
        };
        /**
         * PricesCommissionsSectionResponse
         * @description Ответ секции «Цены и комиссии»
         */
        PricesCommissionsSectionResponse: {
            /**
             * Section
             * @description Идентификатор секции.
             */
            section: string;
            /**
             * Generated At
             * Format: date-time
             * @description Момент генерации (UTC).
             */
            generated_at: string;
            /**
             * Row Count
             * @description Количество строк в data.
             */
            row_count: number;
            /**
             * Warnings
             * @description Замечания о точности расчёта (фоллбэки на настройки и т.п.).
             */
            warnings?: string[];
            /** Data */
            data?: components["schemas"]["PricesCommissionsRow"][];
        };
        /**
         * ProductCardRow
         * @description Строка секции карточек товаров (/v3/product/info/list + локальные габариты)
         */
        ProductCardRow: {
            /**
             * Sku
             * @description SKU товара.
             */
            sku?: number | null;
            /**
             * Name
             * @description Название товара.
             */
            name?: string | null;
            /**
             * Offer Id
             * @description Артикул продавца.
             */
            offer_id?: string | null;
            /**
             * Price
             * @description Цена карточки, ₽.
             */
            price?: number | null;
            /**
             * Old Price
             * @description Старая цена, ₽.
             */
            old_price?: number | null;
            /**
             * Min Price
             * @description Мин. цена, ₽.
             */
            min_price?: number | null;
            /**
             * Volume Weight L
             * @description Объёмный вес, л (из API).
             */
            volume_weight_l?: number | null;
            /**
             * Commission Fbo Percent
             * @description Комиссия FBO, %.
             */
            commission_fbo_percent?: number | null;
            /**
             * Commission Fbs Percent
             * @description Комиссия FBS, %.
             */
            commission_fbs_percent?: number | null;
            /**
             * Delivery Fbo
             * @description Доставка FBO, ₽.
             */
            delivery_fbo?: number | null;
            /**
             * Return Fbo
             * @description Возврат FBO, ₽.
             */
            return_fbo?: number | null;
            /**
             * Local Length Mm
             * @description Длина, мм (локальный справочник).
             */
            local_length_mm?: number | null;
            /**
             * Local Width Mm
             * @description Ширина, мм (локальный справочник).
             */
            local_width_mm?: number | null;
            /**
             * Local Height Mm
             * @description Высота, мм (локальный справочник).
             */
            local_height_mm?: number | null;
            /**
             * Local Weight G
             * @description Вес, г (локальный справочник).
             */
            local_weight_g?: number | null;
            /**
             * Local Volume L
             * @description Габаритный объём L×W×H, л.
             */
            local_volume_l?: number | null;
            /**
             * Oversize
             * @description Крупногабарит: сторона > 500 мм (иная тарифная зона Ozon).
             */
            oversize?: boolean | null;
        };
        /**
         * ProductCardsRequest
         * @description Запрос секции карточек товаров (опциональный список SKU)
         */
        ProductCardsRequest: {
            /**
             * Sku
             * @description Список SKU. Пусто/None — все товары продавца из /v3/product/list.
             */
            sku?: (number | string)[] | null;
        };
        /**
         * ProductCardsSectionResponse
         * @description Ответ секции «Карточки товаров»
         */
        ProductCardsSectionResponse: {
            /**
             * Section
             * @description Идентификатор секции.
             */
            section: string;
            /**
             * Generated At
             * Format: date-time
             * @description Момент генерации (UTC).
             */
            generated_at: string;
            /**
             * Row Count
             * @description Количество строк в data.
             */
            row_count: number;
            /**
             * Warnings
             * @description Замечания о точности расчёта (фоллбэки на настройки и т.п.).
             */
            warnings?: string[];
            /** Data */
            data?: components["schemas"]["ProductCardRow"][];
        };
        /**
         * ReportRequest
         * @description Запрос на формирование полного аналитического отчёта
         */
        ReportRequest: {
            /**
             * Date From
             * @description Start date in %Y-%m-%d format
             */
            date_from: string;
            /**
             * Date To
             * @description End date in %Y-%m-%d format
             */
            date_to: string;
        };
        /**
         * ReportStatusResponse
         * @description Статус формирования отчёта
         */
        ReportStatusResponse: {
            /**
             * Request Uuid
             * @description Report request UUID
             */
            request_uuid: string;
            /**
             * Status
             * @description pending | in_progress | completed | failed
             */
            status: string;
            /**
             * Info
             * @description Additional info or error message
             */
            info?: string | null;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * SearchQueriesSectionResponse
         * @description Ответ секции «Поисковые фразы»
         */
        SearchQueriesSectionResponse: {
            /**
             * Section
             * @description Идентификатор секции.
             */
            section: string;
            /**
             * Generated At
             * Format: date-time
             * @description Момент генерации (UTC).
             */
            generated_at: string;
            /**
             * Row Count
             * @description Количество строк в data.
             */
            row_count: number;
            /**
             * Warnings
             * @description Замечания о точности расчёта (фоллбэки на настройки и т.п.).
             */
            warnings?: string[];
            /**
             * Date From
             * @description Начало периода (YYYY-MM-DD).
             */
            date_from: string;
            /**
             * Date To
             * @description Конец периода (YYYY-MM-DD).
             */
            date_to: string;
            /** Data */
            data?: components["schemas"]["SearchQueryRow"][];
        };
        /**
         * SearchQueryRow
         * @description Строка секции поисковых фраз (/v1/analytics/product-queries)
         */
        SearchQueryRow: {
            /**
             * Phrase
             * @description Поисковая фраза.
             */
            phrase?: string | null;
            /**
             * Sku
             * @description SKU товара.
             */
            sku?: number | null;
            /**
             * Offer Id
             * @description Артикул продавца.
             */
            offer_id?: string | null;
            /**
             * Category
             * @description Категория запроса.
             */
            category?: string | null;
            /**
             * Gmv
             * @description Доход по запросу, ₽.
             */
            gmv?: number | null;
            /**
             * Position
             * @description Средняя позиция товара в поиске.
             */
            position?: number | null;
            /**
             * Unique Search Users
             * @description Уникальные пользователи поиска.
             */
            unique_search_users?: number | null;
            /**
             * Unique View Users
             * @description Уникальные пользователи карточки.
             */
            unique_view_users?: number | null;
            /**
             * View Conversion
             * @description Конверсия из поиска в карточку, %.
             */
            view_conversion?: number | null;
        };
        /** SecretsResponse */
        SecretsResponse: {
            /**
             * Seller Client Id
             * @description Ozon Seller API Client ID
             */
            seller_client_id?: string | null;
            /**
             * Seller Api Key
             * @description Ozon Seller API Key
             */
            seller_api_key?: string | null;
            /**
             * Performance Client Id
             * @description Ozon Performance API Client ID
             */
            performance_client_id?: string | null;
            /**
             * Performance Secret
             * @description Ozon Performance API Secret
             */
            performance_secret?: string | null;
            /**
             * Seller Valid
             * @description Валидность Seller API ключей
             * @default false
             */
            seller_valid: boolean;
            /**
             * Performance Valid
             * @description Валидность Performance API ключей
             * @default false
             */
            performance_valid: boolean;
        };
        /** SecretsUpdate */
        SecretsUpdate: {
            /** Seller Client Id */
            seller_client_id?: string | null;
            /** Seller Api Key */
            seller_api_key?: string | null;
            /** Performance Client Id */
            performance_client_id?: string | null;
            /** Performance Secret */
            performance_secret?: string | null;
        };
        /**
         * SellerRatingRow
         * @description Строка секции рейтинга продавца (/v1/rating/summary)
         */
        SellerRatingRow: {
            /**
             * Group Name
             * @description Группа рейтинга.
             */
            group_name?: string | null;
            /**
             * Rating Type
             * @description Тип рейтинга.
             */
            rating_type?: string | null;
            /**
             * Score
             * @description Текущий балл.
             */
            score?: number | null;
            /**
             * Description
             * @description Описание.
             */
            description?: string | null;
        };
        /**
         * SellerRatingSectionResponse
         * @description Ответ секции «Рейтинг продавца»
         */
        SellerRatingSectionResponse: {
            /**
             * Section
             * @description Идентификатор секции.
             */
            section: string;
            /**
             * Generated At
             * Format: date-time
             * @description Момент генерации (UTC).
             */
            generated_at: string;
            /**
             * Row Count
             * @description Количество строк в data.
             */
            row_count: number;
            /**
             * Warnings
             * @description Замечания о точности расчёта (фоллбэки на настройки и т.п.).
             */
            warnings?: string[];
            /** Data */
            data?: components["schemas"]["SellerRatingRow"][];
        };
        /** SettingsResponse */
        SettingsResponse: {
            /**
             * Tax System
             * @description Система налогообложения
             * @default usn_6
             */
            tax_system: string;
            /**
             * Ad Budget Percent
             * @description Бюджет на рекламу, % от выручки
             * @default 5
             */
            ad_budget_percent: number;
            /**
             * Logistics Cost
             * @description Средняя стоимость логистики за заказ, ₽
             * @default 150
             */
            logistics_cost: number;
            /**
             * Cost Price Share
             * @description Оценка себестоимости как доля от цены продажи (Ozon API не отдаёт закупочную цену)
             * @default 0.5
             */
            cost_price_share: number;
            /**
             * Fbo
             * @description FBO (true) или FBS (false)
             * @default false
             */
            fbo: boolean;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /**
             * Tax System
             * @description Система налогообложения
             */
            tax_system?: string | null;
            /**
             * Ad Budget Percent
             * @description Бюджет на рекламу, % от выручки
             */
            ad_budget_percent?: number | null;
            /**
             * Logistics Cost
             * @description Средняя стоимость логистики за заказ, ₽
             */
            logistics_cost?: number | null;
            /**
             * Cost Price Share
             * @description Оценка себестоимости как доля от цены продажи
             */
            cost_price_share?: number | null;
            /**
             * Fbo
             * @description FBO (true) или FBS (false)
             */
            fbo?: boolean | null;
        };
        /**
         * StockPlanningRow
         * @description Строка секции планирования поставок (/v1/analytics/turnover/stocks)
         */
        StockPlanningRow: {
            /**
             * Sku
             * @description SKU товара.
             */
            sku?: number | null;
            /**
             * Name
             * @description Название товара.
             */
            name?: string | null;
            /**
             * Offer Id
             * @description Артикул продавца.
             */
            offer_id?: string | null;
            /**
             * Current Stock
             * @description Текущий остаток, шт.
             */
            current_stock?: number | null;
            /**
             * Ads
             * @description Среднесуточные продажи за 60 дней, шт/день.
             */
            ads?: number | null;
            /**
             * Days Of Stock
             * @description Дней запаса (текущий остаток / ADS).
             */
            days_of_stock?: number | null;
            /**
             * Idc
             * @description Индекс достаточности Ozon, дней.
             */
            idc?: number | null;
            /**
             * Idc Grade
             * @description Оценка достаточности Ozon.
             */
            idc_grade?: string | null;
            /**
             * Turnover
             * @description Оборачиваемость Ozon, дней.
             */
            turnover?: number | null;
            /**
             * Recommended Stock
             * @description Рекомендуемая поставка, шт.
             */
            recommended_stock?: number | null;
            /**
             * Recommended Units
             * @description Рекомендуемая поставка, целых шт.
             */
            recommended_units?: number | null;
            /**
             * Needs Reorder
             * @description Нужна поставка: остатка < заданного порога дней.
             * @default false
             */
            needs_reorder: boolean;
            /**
             * Priority
             * @description critical / low / normal / no-velocity.
             * @default normal
             */
            priority: string;
            /**
             * Due By
             * @description Дата ухода остатка в ноль (YYYY-MM-DD).
             */
            due_by?: string | null;
            /**
             * Warehouses
             * @description Разбивка остатка по складам (/v4/product/info/stocks).
             */
            warehouses?: components["schemas"]["StockWarehouseRow"][];
        };
        /**
         * StockPlanningSectionResponse
         * @description Ответ секции «Планирование поставок»
         */
        StockPlanningSectionResponse: {
            /**
             * Section
             * @description Идентификатор секции.
             */
            section: string;
            /**
             * Generated At
             * Format: date-time
             * @description Момент генерации (UTC).
             */
            generated_at: string;
            /**
             * Row Count
             * @description Количество строк в data.
             */
            row_count: number;
            /**
             * Warnings
             * @description Замечания о точности расчёта (фоллбэки на настройки и т.п.).
             */
            warnings?: string[];
            /**
             * Target Days
             * @description Целевой запас, дней (настройка).
             * @default 30
             */
            target_days: number;
            /**
             * Critical Days
             * @description Порог критического запаса, дней.
             * @default 14
             */
            critical_days: number;
            /** @description Сводка плана поставки. */
            plan_summary?: components["schemas"]["PlanSummary"];
            /** Data */
            data?: components["schemas"]["StockPlanningRow"][];
        };
        /**
         * StockWarehouseRow
         * @description Остаток SKU на конкретном складе
         */
        StockWarehouseRow: {
            /**
             * Name
             * @description Название склада.
             */
            name?: string | null;
            /**
             * Present
             * @description Доступно, шт.
             */
            present?: number | null;
            /**
             * Reserved
             * @description Зарезервировано, шт.
             */
            reserved?: number | null;
        };
        /**
         * TokenResponse
         * @description Ответ с JWT-токеном
         */
        TokenResponse: {
            /**
             * Access Token
             * @description JWT access token
             */
            access_token: string;
            /**
             * Token Type
             * @description Token type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Token expiration in seconds
             */
            expires_in: number;
        };
        /**
         * TopActionItem
         * @description Одно агрегированное действие
         */
        TopActionItem: {
            /**
             * Action Type
             * @description restock / dead_stock / high_costs / search_no_sales.
             */
            action_type: string;
            /**
             * Title
             * @description Человекочитаемый заголовок действия.
             */
            title: string;
            /**
             * Priority
             * @description critical / high / medium / low.
             */
            priority: string;
            /**
             * Sku Count
             * @description Сколько SKU затронуто.
             */
            sku_count: number;
            /**
             * Skus
             * @description Затронутые SKU (первые 20).
             */
            skus?: number[];
            /**
             * Impact
             * @description Краткая оценка последствий/объёма.
             */
            impact: string;
            /**
             * Details
             * @description Сырые данные для UI.
             */
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * TopActionsRequest
         * @description Запрос топ-действий (даты включают анализ поисковых фраз)
         */
        TopActionsRequest: {
            /**
             * Date From
             * @description YYYY-MM-DD (опционально).
             */
            date_from?: string | null;
            /**
             * Date To
             * @description YYYY-MM-DD (опционально).
             */
            date_to?: string | null;
        };
        /**
         * TopActionsResponse
         * @description Ответ: ранжированный список действий
         */
        TopActionsResponse: {
            /**
             * Section
             * @description Идентификатор секции.
             */
            section: string;
            /**
             * Generated At
             * Format: date-time
             * @description Момент генерации (UTC).
             */
            generated_at: string;
            /**
             * Row Count
             * @description Количество строк в data.
             */
            row_count: number;
            /**
             * Warnings
             * @description Замечания о точности расчёта (фоллбэки на настройки и т.п.).
             */
            warnings?: string[];
            /** Actions */
            actions?: components["schemas"]["TopActionItem"][];
        };
        /**
         * UserLogin
         * @description Запрос на вход
         */
        UserLogin: {
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Password
             * @description Password
             */
            password: string;
        };
        /**
         * UserRegister
         * @description Запрос на регистрацию
         */
        UserRegister: {
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Password
             * @description Password
             */
            password: string;
        };
        /**
         * UserResponse
         * @description Ответ с данными пользователя (без пароля)
         */
        UserResponse: {
            /**
             * Id
             * @description User ID
             */
            id: number;
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Is Active
             * @description Is account active
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Account creation date
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_analogs_api_analogs_get: {
        parameters: {
            query: {
                /** @description SKU товара, для которого ищем аналоги. */
                sku: number;
                /** @description Сколько аналогов вернуть. */
                top?: number;
                /** @description Минимальная близость названий. */
                min_similarity?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalogsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_unit_economics_api_calculator_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalculatorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_onboarding_status_api_onboarding_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingStatusResponse"];
                };
            };
        };
    };
    check_connection_api_onboarding_check_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_settings_api_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_secrets_api_secrets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretsResponse"];
                };
            };
        };
    };
    update_secrets_api_secrets_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_secrets_api_secrets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_secrets_api_secrets_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_full_report_api_reports_full_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prices_commissions_api_reports_sections_prices_commissions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricesCommissionsSectionResponse"];
                };
            };
        };
    };
    get_product_cards_api_reports_sections_product_cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ProductCardsRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductCardsSectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_finance_expenses_api_reports_sections_finance_expenses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinanceExpensesSectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_seller_rating_api_reports_sections_seller_rating_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellerRatingSectionResponse"];
                };
            };
        };
    };
    get_stock_planning_api_reports_sections_stocks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockPlanningSectionResponse"];
                };
            };
        };
    };
    get_search_queries_api_reports_sections_search_queries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchQueriesSectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cashflow_api_reports_sections_cashflow_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashFlowSectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_actions_api_reports_top_actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TopActionsRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopActionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_status_api_reports_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
